### ISSUE TITLE
package for Ubuntu Touch

### ISSUE THREAD

**Issue by lduboeuf** [cizum/sweeper-madness#2]
Hello,

Thanks for your project. I would like to package it for Ubuntu Touch, are you agree with that and what Licence should i specify ?

**Comment by cizum** [comment]
Hello,

Yes, I agree
Code was updated and a MIT license was added.

**Comment by lduboeuf** [comment]
Thank you, done, published on Openstore here: https://open-store.io/app/sm.lduboeuf
